### ISSUE TITLE
Problème affichage

### ISSUE THREAD

**Issue by arsiak** [IFATech-Metz/dev-log-8#7]
- Seul le titre s'affiche lorsqu'on lance projet.html

**Comment by fab57fr** [comment]
Le projet n'était pas uploadé correctement

**Comment by arsiak** [comment]
- Projet fonctionnel ! 
- Belles animations ! 
- Répond au cahier des charges
- Manque un peu de visibilité avec le texte sur les images

**Comment by MrCapelli** [comment]
Nous te remercions !
